api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header