framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3         
                    delay: 1000             
                    multiplier: 2           
                    max_delay: 10000
            failed: 'doctrine://default?queue_name=failed'  

        routing:
            'App\Message\PostPublishedNotification': async
        
        #Шина с поддержкой транзакций
        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction

when@test:
    framework:
        messenger:
            transports:
                async: 'test://'
