framework:
    messenger:
        transports:
            async: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Message\PostPublishedNotification': async

when@test:
    framework:
        messenger:
            transports:
                async: 'test://'
