vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        user_avatar:
            uri_prefix: /media/avatars
            upload_destination: '%kernel.project_dir%/public/media/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true  
